- hosts: child
  remote_user: pi
  sudo: yes
  gather_facts: no
  tasks:
    - name: apt install pip
      apt:
        name: python-pip
        state: present
    - name: pip install timeout_decorator
      pip:
        name: bottle
